### ISSUE TITLE
 可以监听recylerview滚动并修改indexbar当前选中吗

### ISSUE THREAD

**Issue by GXuLing** [hgDendi/ContactsList#3]

**Comment by hgDendi** [comment]
监听recyclerview的滚动可以设置onScrollListener
但是要知道当前选中暂时想到两个方案:
1.依赖一下具体的LayoutManager,比如LinearLayoutManager#findFirstVisibleItemPosition()，拿到positoin
2.使用recyclerview#getChildAt(0)拿到当前显示的View，通过View转换到对应的indexbar的item

**Comment by GXuLing** [comment]
恩恩,已使用第一种方法实现,谢啦
